apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: istio-system
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: istio
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'


---

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istio-istiod
  namespace: argocd
spec:
  generators:
  - clusters: {}
  template:
    metadata:
      name: istio-istiod
    spec:
      destination:
        namespace: istio-system
        server: https://kubernetes.default.svc
      ignoreDifferences:
      - jsonPointers:
        - /imagePullSecrets
        - /secrets
        kind: ServiceAccount
      project: istio-system
      source:
        helm:
          valueFiles:
          - values-istiod.yaml
        path: .
        repoURL: https://github.com/mgcalvo-istio-demo/istio-istiod-argocd-helm.git
        targetRevision: main
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - Replace=false
        - PruneLast=true
        - CreateNamespace=true
